WIP

diff --git a/tmp/tidy b/tmp/tidy
--- a/tmp/tidy
+++ b/tmp/tidy
@@ -41,7 +41,7 @@ while true; do
   esac
 done
 
-trap cleanup EXIT
+#trap cleanup EXIT
 
 if ! command -v perltidy > /dev/null 2>&1; then
     echo "No perltidy found, install it first!"
@@ -61,7 +61,8 @@ find-files() {
     local files=()
     [[ -d script ]] && files+=(script/*)
     files=($(file --mime-type * "${files[@]}" | grep text/x-perl | awk -F':' '{ print $1 }'))
-    files+=('**.p[ml]' '**.t')
+    #files+=('**.p[ml]' '**.t')
+    files+=('lib/**.p[ml]')
     if $only_changed; then
         git status --porcelain "${files[@]}" | awk '{ print $2 }'
     else
