Add check for invalid syntax is_sle and is_leap
Often we have the problem a new branch in the code is added and some
usage of functions like is_sle and is_leap is not entirely consistent.
While this is fixed, we can simply stop from merging PR's that have such
invalid syntax

diff --git a/tools/check_invalid_syntax b/tools/check_invalid_syntax
--- a/tools/check_invalid_syntax
+++ b/tools/check_invalid_syntax
@@ -1,11 +1,37 @@
 #!/bin/sh
+
+let exit_code=0
+GIT_CMD="git --no-pager grep --break  --color -n -P"
+
 check_loadtest() {
-    CHECK_LOADTEST_RESULT=$(git --no-pager grep --break -P "\sloadtest\s?\(?(?:\"|')?[\w\/]+\.pm(?:\"|'),?.*\)?")
+    CHECK_LOADTEST_RESULT=$(${GIT_CMD} "\sloadtest\s?\(?(?:\"|')?[\w\/]+\.pm(?:\"|'),?.*\)?")
     if [ ! -z "$CHECK_LOADTEST_RESULT" ]; then
-        echo $CHECK_LOADTEST_RESULT
+        echo "${CHECK_LOADTEST_RESULT}"
         echo "Invalid syntax found for loadtest call. '.pm' extensions are not allowed at test distribution level"
-        return $?
+        let "exit_code++"
     fi
+    echo "Finished checking loadtests"
 }
 
+check_versions(){
+    CHECK_IS_LEAP_RESULT=$(${GIT_CMD} "is_leap.*(\"|')\d{2,}(?!>\.\d)\1")
+    if [ ! -z "$CHECK_IS_LEAP_RESULT" ]; then
+        echo "${CHECK_IS_LEAP_RESULT}"
+        echo "Invalid  call for is_leap"
+        let "exit_code++"
+    fi
+
+    CHECK_IS_SLE_RESULT=$(${GIT_CMD} "is_sle[\(\s](\"|')\d{2,}(?:\.\d\+)\1")
+    if [ ! -z "$CHECK_IS_SLE_RESULT" ]; then
+        echo "${CHECK_IS_SLE_RESULT}"
+        echo "Invalid  call for is_sle"
+        let "exit_code++"
+    fi
+    echo "Finished checking for invalid version syntax"
+}
+
+check_versions
 check_loadtest
+
+echo "All checks finished: $exit_code."
+exit $exit_code;
