Fix isotovideo test by removing colors
https://github.com/os-autoinst/os-autoinst/pull/2134 added colors to
line endings, which make them in fact, different to what the expected
output we have

diff --git a/.github/workflows/ci-isotovideo.yml b/.github/workflows/ci-isotovideo.yml
--- a/.github/workflows/ci-isotovideo.yml
+++ b/.github/workflows/ci-isotovideo.yml
@@ -10,3 +10,6 @@ jobs:
     - uses: actions/checkout@v2
     - name: Run isotovideo tests
       run: make test-isotovideo
+    - name: Error in isotovideo
+      if: ${{ failure() }}
+      run: echo 'isotovideo failed, something modified the default schedule or the output; run locally to find out more.' && exit 1
